/**
 * Curated country patches — typed, segmented config for build-countries.
 *
 * - sourceCorrectionsByIso3: explicit fixes where world-countries / REST disagree with gameplay intent
 * - searchAliasesByIso3: player-facing search variants NOT already in names or REST alternates
 * - wikipediaTitlesByIso3: Wikipedia article title overrides (popularity only)
 * - gameplayClassifications: constraint tag lists (events, geo, physical features, regime)
 * - manualCountryAdditions: countries absent from world-countries (Kosovo XKX → 196 + 1 = 197 playable)
 */
import type { Country } from "../../src/features/countries/types.ts";
import type {
  CountryPatchesConfig,
  GameplayClassifications,
  SourceCorrection,
} from "./buildCountriesLib.ts";

/** ISO 3166-1 alpha-3 — playable country (196 UN + inclusions) or addition like XKX. */
export type Iso3 = string;

// ─── Source corrections (borders, waterAccess only) ───────────────────────────

export const sourceCorrectionsByIso3: Record<Iso3, SourceCorrection> = {
  /** Tasmania-only border count would mark AUS as island; gameplay = coastal mainland. */
  AUS: { waterAccess: "coastal" as const },
  /** Island nation; world-countries lists a land border with India. */
  LKA: { waterAccess: "island" as const, borders: [] },
  /** Kosovo recognition: REST uses UNK, gameplay uses XKX. */
  ALB: { borders: ["MNE", "GRC", "MKD", "XKX"] },
  MKD: { borders: ["ALB", "BGR", "GRC", "XKX", "SRB"] },
  MNE: { borders: ["ALB", "BIH", "HRV", "XKX", "SRB"] },
  SRB: {
    borders: ["BIH", "BGR", "HRV", "HUN", "XKX", "MKD", "MNE", "ROU"],
  },
  /** Exclude GIB: not a playable country, unlike XKX or GUF→FRA border gameplay. */
  ESP: { borders: ["AND", "FRA", "PRT", "MAR"] },
  /** French Guiana counts as metropolitan border for gameplay (REST uses GUF). */
  BRA: {
    borders: [
      "ARG",
      "BOL",
      "COL",
      "FRA",
      "GUY",
      "PRY",
      "PER",
      "SUR",
      "URY",
      "VEN",
    ],
  },
  SUR: { borders: ["BRA", "FRA", "GUY"] },
  FRA: {
    borders: [
      "AND",
      "BEL",
      "BRA",
      "DEU",
      "ITA",
      "LUX",
      "MCO",
      "ESP",
      "SUR",
      "CHE",
    ],
  },
};

// ─── Search aliases (player variants beyond names + REST alternates) ────────────

/** Variants absent from names.{fr,en}, iso codes, and REST official/alternates. */
export const searchAliasesByIso3: Record<Iso3, string[]> = {
  USA: ["Amérique"],
  GBR: ["Angleterre"],
  PRK: ["RPDC"],
  KOR: ["ROK"],
  MKD: ["Macédoine"],
  PSE: ["Territoires palestiniens", "Palestinian Territories"],
  TWN: ["Formose", "Formosa"],
  VAT: ["Saint-Siège"],
  CPV: ["Cap-Vert"],
  IRN: ["Perse"],
  ARE: ["EAU"],
  NLD: ["Hollande"],
};

// ─── Wikipedia title overrides ────────────────────────────────────────────────

export const wikipediaTitlesByIso3: Record<Iso3, string> = {
  BHS: "The_Bahamas",
  CZE: "Czech_Republic",
  COD: "Democratic_Republic_of_the_Congo",
  GEO: "Georgia_(country)",
  GMB: "The_Gambia",
  LIE: "Liechtenstein",
  OMN: "Oman",
  PLW: "Palau",
  PRK: "North_Korea",
  SDN: "Sudan",
  SLB: "Solomon_Islands",
  SLE: "Sierra_Leone",
  SMR: "San_Marino",
  SRB: "Serbia",
  SWE: "Sweden",
  SWZ: "Eswatini",
  THA: "Thailand",
  TON: "Tonga",
  TUN: "Tunisia",
  TUR: "Turkey",
  TZA: "Tanzania",
  URY: "Uruguay",
  UZB: "Uzbekistan",
  VEN: "Venezuela",
  XKX: "Kosovo",
};

// ─── Gameplay classifications (constraint tags) ───────────────────────────────

export const gameplayClassifications: GameplayClassifications = {
  middleEast: [
    "ARE",
    "BHR",
    "CYP",
    "EGY",
    "IRN",
    "IRQ",
    "ISR",
    "JOR",
    "KWT",
    "LBN",
    "OMN",
    "PSE",
    "QAT",
    "SAU",
    "SYR",
    "TUR",
    "YEM",
  ],
  eventFifaWcHost: [
    "URY",
    "ITA",
    "FRA",
    "BRA",
    "CHE",
    "SWE",
    "CHL",
    "GBR",
    "MEX",
    "DEU",
    "ARG",
    "ESP",
    "USA",
    "JPN",
    "KOR",
    "ZAF",
    "RUS",
    "QAT",
  ],
  eventSummerOlympicsHost: [
    "GRC",
    "FRA",
    "USA",
    "GBR",
    "SWE",
    "BEL",
    "NLD",
    "DEU",
    "FIN",
    "AUS",
    "ITA",
    "JPN",
    "MEX",
    "CAN",
    "KOR",
    "ESP",
    "CHN",
    "BRA",
    "RUS",
  ],
  monarchy: [
    "GBR",
    "CAN",
    "AUS",
    "NZL",
    "BHS",
    "ATG",
    "BLZ",
    "GRD",
    "JAM",
    "PNG",
    "KNA",
    "LCA",
    "VCT",
    "SLB",
    "TUV",
    "BEL",
    "DNK",
    "LUX",
    "MCO",
    "NLD",
    "NOR",
    "ESP",
    "SWE",
    "LIE",
    "AND",
    "SAU",
    "ARE",
    "QAT",
    "OMN",
    "KWT",
    "BHR",
    "JOR",
    "MAR",
    "BTN",
    "BRN",
    "JPN",
    "THA",
    "KHM",
    "MYS",
    "LSO",
    "SWZ",
    "TON",
    "VAT",
  ],
  equatorCrosser: [
    "COL",
    "ECU",
    "BRA",
    "STP",
    "GAB",
    "COG",
    "COD",
    "UGA",
    "KEN",
    "IDN",
    "MDV",
    "KIR",
  ],
  mediterraneanCoast: [
    "ESP",
    "FRA",
    "MCO",
    "ITA",
    "MLT",
    "SVN",
    "HRV",
    "BIH",
    "MNE",
    "ALB",
    "GRC",
    "TUR",
    "CYP",
    "SYR",
    "LBN",
    "ISR",
    "PSE",
    "EGY",
    "LBY",
    "TUN",
    "DZA",
    "MAR",
  ],
  caribbeanCoast: [
    "CUB",
    "HTI",
    "DOM",
    "JAM",
    "BHS",
    "TTO",
    "BRB",
    "GRD",
    "VCT",
    "LCA",
    "DMA",
    "ATG",
    "KNA",
    "BLZ",
    "GTM",
    "HND",
    "NIC",
    "CRI",
    "PAN",
    "COL",
    "VEN",
    "MEX",
  ],
  peakOver5000m: [
    "AFG",
    "ARG",
    "BOL",
    "BTN",
    "CAN",
    "CHL",
    "CHN",
    "COL",
    "COD",
    "ECU",
    "GEO",
    "IND",
    "IRN",
    "KAZ",
    "KEN",
    "KGZ",
    "MEX",
    "NPL",
    "PAK",
    "PER",
    "RUS",
    "TJK",
    "TZA",
    "TUR",
    "UGA",
    "USA",
  ],
  capitalNotLargest: [
    "USA",
    "CAN",
    "AUS",
    "BRA",
    "TUR",
    "NGA",
    "ZAF",
    "CHE",
    "MAR",
    "TZA",
    "KAZ",
    "MMR",
    "CIV",
    "CMR",
    "BEN",
    "BDI",
    "BOL",
    "ECU",
    "VNM",
    "NZL",
    "BLZ",
    "PHL",
    "LKA",
    "PAK",
    "PLW",
    "FSM",
  ],
  desert: [
    "DZA",
    "LBY",
    "EGY",
    "SDN",
    "TCD",
    "NER",
    "MLI",
    "MRT",
    "MAR",
    "TUN",
    "SAU",
    "ARE",
    "OMN",
    "YEM",
    "KWT",
    "QAT",
    "JOR",
    "IRQ",
    "SYR",
    "ISR",
    "IRN",
    "TKM",
    "UZB",
    "KAZ",
    "MNG",
    "CHN",
    "IND",
    "PAK",
    "AFG",
    "USA",
    "MEX",
    "CHL",
    "PER",
    "ARG",
    "BOL",
    "NAM",
    "BWA",
    "ZAF",
    "AGO",
    "AUS",
  ],
  rainforest: [
    "BRA",
    "PER",
    "COL",
    "ECU",
    "VEN",
    "BOL",
    "GUY",
    "SUR",
    "COD",
    "COG",
    "GAB",
    "CMR",
    "GNQ",
    "IDN",
    "MYS",
    "PNG",
    "PHL",
    "THA",
    "VNM",
    "MMR",
    "BRN",
    "LAO",
    "KHM",
    "IND",
    "LKA",
    "CRI",
    "PAN",
    "MDG",
  ],
  atlanticCoast: [
    "ISL",
    "IRL",
    "GBR",
    "FRA",
    "ESP",
    "PRT",
    "NOR",
    "NLD",
    "BEL",
    "DEU",
    "DNK",
    "MAR",
    "MRT",
    "SEN",
    "GMB",
    "GNB",
    "GIN",
    "SLE",
    "LBR",
    "CIV",
    "GHA",
    "TGO",
    "BEN",
    "NGA",
    "CMR",
    "GNQ",
    "GAB",
    "COG",
    "COD",
    "AGO",
    "NAM",
    "ZAF",
    "CPV",
    "STP",
    "CAN",
    "USA",
    "MEX",
    "BRA",
    "URY",
    "ARG",
    "GUY",
    "SUR",
    "VEN",
  ],
  pacificCoast: [
    "CAN",
    "USA",
    "MEX",
    "GTM",
    "SLV",
    "HND",
    "NIC",
    "CRI",
    "PAN",
    "COL",
    "ECU",
    "PER",
    "CHL",
    "RUS",
    "CHN",
    "KOR",
    "PRK",
    "JPN",
    "TWN",
    "PHL",
    "VNM",
    "IDN",
    "MYS",
    "BRN",
    "SGP",
    "THA",
    "KHM",
    "TLS",
    "AUS",
    "NZL",
    "PNG",
    "FJI",
    "SLB",
    "VUT",
    "WSM",
    "TON",
    "KIR",
    "TUV",
    "NRU",
    "MHL",
    "FSM",
    "PLW",
  ],
  indianOceanCoast: [
    "ZAF",
    "MOZ",
    "TZA",
    "KEN",
    "SOM",
    "MDG",
    "MUS",
    "SYC",
    "COM",
    "SAU",
    "YEM",
    "OMN",
    "ARE",
    "QAT",
    "BHR",
    "KWT",
    "IRQ",
    "IRN",
    "PAK",
    "IND",
    "BGD",
    "LKA",
    "MDV",
    "MMR",
    "THA",
    "IDN",
    "MYS",
    "AUS",
  ],
};

// ─── Manual country additions ─────────────────────────────────────────────────

export const manualCountryAdditions: Country[] = [
  {
    iso3: "XKX",
    iso2: "XK",
    names: { fr: "Kosovo", en: "Kosovo" },
    aliases: [],
    flagEmoji: "🇽🇰",
    continent: "europe",
    waterAccess: "landlocked",
    borders: ["ALB", "MKD", "MNE", "SRB"],
    areaKm2: 10887,
    population: 1585566,
    officialLanguages: ["sq", "sr"],
    latitude: 42.6,
    subregion: "Southeast Europe",
    flagColors: ["blue", "yellow", "white"],
    flagSymbols: ["star"],
    flagLayout: [],
    events: [],
    memberships: [],
    capitals: [
      {
        name: "Pristina",
        latitude: 42.6629,
        longitude: 21.1655,
        roles: ["primary"],
      },
    ],
    drivingSide: "right",
    geoTags: [],
    regime: "republic",
    physicalFeatures: [],
  },
];

export const countryPatches: CountryPatchesConfig = {
  sourceCorrectionsByIso3,
  searchAliasesByIso3,
  wikipediaTitlesByIso3,
  gameplayClassifications,
  manualCountryAdditions,
};
